name: goreleaser

on:
  push:
    tags:
      - 'v*.*.*'

# Pushes a new release on tag
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    name: goreleaser
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Unshallow
        run: git fetch --prune --unshallow
      - name: Set up Go
        uses: actions/setup-go@v2-beta
        with:
          stable: 'false'
          go-version: '1.14.0-rc1'
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
